print(' 1. Ler dois números e imprimir as variáveis na mesma ordem que foram digitadas.')
numeroUm = int(input('Digite um número: '))
numeroDois = int(input('Digite outro numero: '))
print(f'{numeroUm} e {numeroDois}')
print('1.a. Ler dois números e imprimir as variáveis na ordem inversa que foram digitadas.')
numUm = int(input('Digite um número: '))
numDois = int(input('Digite outro numero: '))
print(f'{numDois} e {numUm}')
print('2. Ler dois valores numéricos e escrever a soma destes.')
numberOne = int(input('Digite um numero: '))
numberTwo = int(input('Digite outro número: '))
print(f'{numberOne + numberTwo}')
print('3. Ler dois valores numéricos e escrever a  subtração destes.')
numberUno = int(input('Digite um numero: '))
numberDos = int(input('Digite outro número: '))
print(f'{numberUno - numberDos}')
print("4.Ler dois valores numéricos e escrever a  multiplicação destes.")
numeroUno = int(input('Digite um numero: '))
numeroDos = int(input('Digite outro número: '))
print(f'{numeroUno * numeroDos}')
print ('5.Ler dois valores numéricos e escrever a  divisão destes.')
numerUm = int(input('Digite um numero: '))
numerDois = int(input('Digite outro número: '))
print(f'{numerUm / numerDois}')
print(f'{numerUm // numerDois}')
print('6. Ler três valores numéricos e escrever a média aritmética.')
numeUm = int(input('Digite um numero: '))
numeDois = int(input('Digite outro número: '))
numeTres = int(input('Digite mais um numero: '))
print(f'{(numeUm+numeDois+numeTres)/3}')
print('7. Ler um conjunto de 5 dados numéricos e imprimir sua soma e sua média.')
nUm = int(input('Digite um numero: '))
nDois = int(input('Digite um numero: '))
nTres = int(input('Digite um numero: '))
nQuatro = int(input('Digite um numero: '))
nCinco = int(input('Digite um numero: '))
soma = nUm + nDois + nTres + nQuatro + nCinco
print(f'A média da soma {soma} é {soma / 5}')
print(f'8. Escreva um algoritmo que leia dois números que deverão ser colocados, respectivamente nas variáveis a e b.')
a = int(input('Digite um numero: '))
b = int(input('Digite um numero: '))
print('O algoritmo deve, então, trocar os valores de a por b e vice-versa.')
print(f'{a} e {b}')
x = a
a = b
b = x
print('Mostrar o conteúdo destas variáveis conforme a ordem de digitação antes da troca e após a troca.')
print(f'{a} e {b}')
