print('Exercícios com while e do-while')
print('5) Faça um programa que simule a urna eletrônica.')
print('A tela a ser apresentada deverá ser da seguinte forma:')
print('As opcoes sao:')
print('1. Candidato Jair Rodrigues')
print('2. Candidato Carlos Luz')
print('3. Candidato Neves Rocha')
print('4. Nulo')
print('5. Branco')
print('Entre com o seu voto:')
print('O programa deverá ler os votos dos eleitores e, quando for entrado o número 6, apresentar as seguintes')
print('informações:')
print('a) O número de votos de cada candidato;')
print('b) A porcentagem de votos nulos;')
print('c) A porcentagem de votos brancos;')
print('d) O candidato vencedor.')